[project]
name = "mathorcup-25"
version = "0.1.0"
description = "YOLO training utilities for MathOrCup 2025"
authors = [
    {name = "chendaile",email = "3185854290@qq.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ultralytics (>=8.3.221,<9.0.0)",
    "tensorboard (>=2.20.0,<3.0.0)",
    "clearml (>=2.0.2,<3.0.0)"
]

[project.scripts]
mathorcup-train = "mathorcup_25.train:main"


[tool.poetry]
packages = [
    {include = "mathorcup_25", from = "src"}
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
