[tool.poetry]
name = "mathorcup-25"
version = "0.2.0"
description = "YOLO training utilities for MathOrCup 2025"
authors = ["chendaile <3185854290@qq.com>"]
readme = "README.md"
packages = [
    {include = "mathorcup_25", from = "src"}
]

[tool.poetry.dependencies]
clearml = ">=2.0.2,<3.0.0"
python = ">=3.10,<3.15" 

[tool.poetry.scripts]
mathorcup-train-yolo = "mathorcup_25.train_yolo:main"
mathorcup-inference-yolo = "mathorcup_25.inference_yolo:main"
show-diff = "mathorcup_25.showdiff_GenerativeAdversarial_models:main"
train-split = "mathorcup_25.train_split:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"